Adds Email Confirmation, KYC procedure, Password Reset and Disable Operator modules.
blockydevs/human-protocol pull request #64
Opened 2024-04-24 12:54 UTC by MWBlocky

## Description

This Pull Request adds the Email Confirmation, KYC procedure, Password Reset and Disable Operator modules.

## Summary of changes
- Integration with new modules.
- Added Swagger docs.
- Units tests.

2024-04-24 12:59 UTC, BartoszSolkaBD approved these changes

2024-04-24 15:17 UTC, macnablocky requested changes

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
> +    const restorePasswordDto = this.mapper.map(
restorePasswordData

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/disable-operator/model/prepare-signature.model.ts
> +  type: string;
shouldn't this be enum

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.controller.spec.ts
> +  it('should return the proper response from processPrepareSignature', async () => {
why are you testing service in controller suite,  more importantly, you are calling mocked service - so this test don't check anything

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.fixtures.ts
> +const TYPE: PrepareSignatureType = PrepareSignatureType.SIGNUP;
in test suite you define this as enum whereas in model this is string

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.fixtures.ts
> +  from: 'string',
why this is not defined as Constant

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/email-confirmation/email-confirmation.controller.ts
> +  @Post('/email-confirmation/email-verification')
define /email-confirmation as controller level

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/email-confirmation/email-confirmation.controller.ts
> +    private readonly emailConfirmationService: EmailConfirmationService,
there is no other service used here, this may be just 'service'

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.service.mock.ts
> +    .mockReturnValue(prepareSignatureResponseFixture),
in my opinion this should just define methods as mocked and not define returned value

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/email-confirmation/spec/email-verification.controller.spec.ts
> +      const dto: EmailVerificationDto = {
to fixture

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/email-confirmation/spec/email-verification.service.spec.ts
> +      const command: EmailVerificationCommand = {
to fixture

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/kyc-procedure/kyc-procedure.service.ts
> +  constructor(private reputationOracleService: ReputationOracleGateway) {}
gateway/reputationOracleGateway

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/password-reset/model/restore-password.model.ts
> +  h_captcha_token: string;
hCaptchaToken

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +      createMap(mapper, RestorePasswordCommand, RestorePasswordData);
align mapper

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +      createMap(mapper, RestorePasswordDto, RestorePasswordCommand);
align mapper

2024-04-24 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
> +  async sendEmailVerification(
where are tests for this

2024-04-25 09:27 UTC, MWBlocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
> +    const restorePasswordDto = this.mapper.map(
fix: 20086ff6

2024-04-25 09:33 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/disable-operator/model/prepare-signature.model.ts
> +  type: string;
fix: 4a83a785

2024-04-25 09:34 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.fixtures.ts
> +const TYPE: PrepareSignatureType = PrepareSignatureType.SIGNUP;
rel: 4a83a785

2024-04-25 09:48 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.controller.spec.ts
> +  it('should return the proper response from processPrepareSignature', async () => {
fix: b5c63a66

2024-04-25 09:48 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.fixtures.ts
> +  from: 'string',
fix: b5c63a66

2024-04-25 09:50 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/disable-operator/spec/disable-operator.service.mock.ts
> +    .mockReturnValue(prepareSignatureResponseFixture),
rel: b5c63a66

2024-04-25 09:58 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/email-confirmation/email-confirmation.controller.ts
> +    private readonly emailConfirmationService: EmailConfirmationService,
fix: 2c8c15c9

2024-04-25 10:01 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/kyc-procedure/kyc-procedure.service.ts
> +  constructor(private reputationOracleService: ReputationOracleGateway) {}
fix: cef2dc8d

2024-04-25 10:14 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/email-confirmation/email-confirmation.controller.ts
> +  @Post('/email-confirmation/email-verification')
fix: aa1e065d

2024-04-25 10:39 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/email-confirmation/spec/email-verification.service.spec.ts
> +      const command: EmailVerificationCommand = {
fix: ccb46f2d

2024-04-25 10:39 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/email-confirmation/spec/email-verification.controller.spec.ts
> +      const dto: EmailVerificationDto = {
fix: ccb46f2d

2024-04-25 10:51 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +      createMap(mapper, RestorePasswordCommand, RestorePasswordData);
fix: 0d7453c8

2024-04-25 10:52 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +      createMap(mapper, RestorePasswordDto, RestorePasswordCommand);
fix: 0d7453c8

2024-04-26 09:16 UTC, MWBlocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
> +  async sendEmailVerification(
fix: b2fb8620

2024-04-26 10:26 UTC, macnablocky approved these changes
only minor fixes remain

2024-04-26 10:26 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +          (destination) => destination.h_captcha_token,
direct mappings are not necessary

2024-04-26 10:26 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +          (destination) => destination.hCaptchaToken,
direct mappings are not necessary

2024-04-26 10:26 UTC, macnablocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/reputation-oracle.gateway.ts
> -  async resendSendEmailVerification(
imo previous method name was better

2024-04-26 10:48 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +          (destination) => destination.hCaptchaToken,
fix: 6731508

2024-04-26 10:48 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/password-reset/password-reset.mapper.ts
> +          (destination) => destination.h_captcha_token,
fix: 6731508

2024-05-13 11:52 UTC, BartoszSolkaBD approved these changes

2024-05-13 11:52 UTC, merged