4th milestone features
blockydevs/human-protocol pull request #79
Opened 2024-05-13 06:40 UTC by macnablocky

## Description
### Adds 4th milestone related features: 
#### H-Captcha labeling enpoints: 
    * /enable - this will be a proxy to Reputation Oracle
    * /verify - an endpoint that sends the user solution of the job to Captcha
    * /daily-hmt-spent - an endpoint that returns global daily HMT spent (will be cached in Redis)
    * /user-stats - an endpoint that returns stats per user (will be cached in Redis)
#### H-Captcha labeling gateway
### TODO: 
* Add unit tests
* Add proxy enpoints for: user/register-address and auth/signin/web3
* Perform additional manual tests

2024-05-13 08:23 UTC, BartoszSolkaBD requested changes

2024-05-13 08:23 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/modules/h-captcha/h-captcha.service.ts
> +    let message = 'Failed to verify h-captcha token. ';
remove trailing space

2024-05-13 08:23 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/modules/h-captcha/h-captcha.service.ts
> +      this.cacheManager.set(hmtKey, dailyHmtSpent);
set TTL on cache (taken from env)

2024-05-13 08:23 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/modules/h-captcha/h-captcha.service.ts
> +      await this.cacheManager.set(command.email, stats);
set TTL on cache (taken from env)

2024-05-13 08:53 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/h-captcha/h-captcha.service.ts
> +    let message = 'Failed to verify h-captcha token. ';
I append to this message

2024-05-14 19:39 UTC, macnablocky commented on packages/apps/reputation-oracle/server/vercel.json
> +    {
@MWBlocky : trochę się nie znam na vercelu: czy tutaj jest cos do dopisania w związku z nowymi endpointami

2024-05-15 11:25 UTC, BartoszSolkaBD requested changes
please check vercel.json with @MWBlocky

2024-05-15 11:25 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/common/config/environment-config.service.ts
> +    return this.configService.getOrThrow<string>('JWT_SECRET'); // TODO: probably to remove
?

2024-05-15 11:25 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/common/config/environment-config.service.ts
> +  }
add these two as required in validation schema in app.module.ts

2024-05-15 14:38 UTC, MWBlocky requested changes
not all tests pass

2024-05-15 14:38 UTC, MWBlocky commented on packages/apps/human-app/server/src/modules/oracle-discovery/oracle-discovery.mapper.profile.ts
> +} from './model/oracle-discovery.model';
oracle-discovery.model has no exported member 'OracleDiscoveryCommand' and 'OracleDiscoveryDto'

2024-05-15 14:38 UTC, MWBlocky commented on packages/apps/human-app/server/src/app.module.ts
> +    HCaptchaController,
controller could be defined from the module it belongs to

2024-05-15 14:38 UTC, MWBlocky commented on packages/apps/human-app/server/src/integrations/h-captcha-labeling/h-captcha-labeling.mapper.profile.ts
> +} from '../../modules/h-captcha/model/user-sats.model';
user-stats?

2024-05-15 14:38 UTC, MWBlocky commented on packages/apps/human-app/server/src/integrations/reputation-oracle/spec/reputation-oracle.gateway.spec.ts
> +        of(prepareSignatureResponseFixture),
of({ data: prepareSignatureResponseFixture }),

2024-05-15 15:17 UTC, macnablocky commented on packages/apps/human-app/server/src/integrations/h-captcha-labeling/h-captcha-labeling.mapper.profile.ts
> +} from '../../modules/h-captcha/model/user-sats.model';
What about them?

2024-05-21 06:12 UTC, macnablocky commented on packages/apps/human-app/server/src/app.module.ts
> +    HCaptchaController,
This would be precedence - drop: to consider in bigger refactoring

2024-06-20 11:14 UTC, BartoszSolkaBD commented on packages/apps/reputation-oracle/server/vercel.json
>      }
What's that about?

2024-06-20 12:24 UTC, BartoszSolkaBD requested changes

2024-06-20 12:24 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/modules/h-captcha/model/user-stats.model.ts
> +  balance: BalanceStats; // what about this
what about this comment?

2024-06-20 12:24 UTC, BartoszSolkaBD commented on packages/apps/human-app/server/src/modules/h-captcha/model/user-stats.model.ts
> +  currentEarningsStats: DateValue; // what about this
what about this comment?

2024-06-20 13:19 UTC, macnablocky commented on packages/apps/human-app/server/src/modules/h-captcha/model/user-stats.model.ts
> +  balance: BalanceStats; // what about this
I didn't know if this is proper structure as I looked suspicious, same for the comment below, I am removing this comment and resolving remarks for this issue

2024-06-20 13:30 UTC, BartoszSolkaBD approved these changes

2024-06-20 13:34 UTC, merged